import PageTemplate from '../components/PageTemplate';

const title = 'Help';

function HelpPage(): JSX.Element {
  return (
    <PageTemplate title={title}>
      <h1>{title}</h1>
      <div>
        <p>Eleifend accusantium class vehicula, quis dapibus voluptatum hymenaeos mus turpis. Perferendis saepe! Tincidunt? Ullam sem officiis? Voluptatem saepe? Officia aut aspernatur! Dictumst provident? Felis sollicitudin corporis consectetur dicta senectus ducimus illo montes! Nonummy, cupidatat magna nobis perspiciatis tempora consectetuer totam. Libero pharetra, doloribus voluptates molestias voluptate ac curae, dolorem! Mollit, proident class. Torquent ultricies, ratione pariatur? Ac orci? Sint odit.</p>
        <p>Voluptates senectus natus vero! Nisl magna sint congue officia feugiat, laboris facilisis. Lobortis adipisci vehicula iure nisi! Aliqua quisque nisi incididunt, vel nobis animi. Fringilla perferendis quibusdam accusamus vel praesent, etiam reiciendis etiam, metus, etiam neque. Adipisci veritatis sociosqu, quae ipsum libero? Malesuada soluta bibendum! Primis! Tempus numquam, pellentesque orci luctus, nostrum dicta delectus nascetur earum, maecenas neque nam! Irure.</p>
        <p>Harum sint incidunt fugiat dis malesuada? Morbi reprehenderit hac rem, quaerat eos? Taciti provident, itaque facilisis penatibus torquent incididunt, eos, doloremque vehicula lobortis! Non repellendus congue? Tincidunt recusandae per cumque? Eiusmod eum aliqua sagittis mollit eligendi? Varius parturient habitasse, ullamco quidem orci. Risus sint, sapiente. Congue eleifend adipisci, magnam delectus montes adipisicing, optio libero. Vel. Temporibus facilisis, faucibus hendrerit debitis.</p>
        <p>Recusandae anim sem do natus nullam dolores gravida vivamus saepe proin adipisci consequuntur platea, platea eget. Pellentesque temporibus! Dolore aliquip taciti venenatis minim ac, duis distinctio magna orci! Eius at, dui dapibus euismod! Magnam aute voluptatibus? Ante impedit dolores primis officia, fuga. Ut reiciendis risus eget! Cubilia facilis! Dolore etiam ratione minus lacinia anim! Venenatis, incididunt? Omnis alias a massa.</p>
        <p>Omnis eiusmod luctus eu nobis iaculis hic ea consequatur, parturient, ridiculus adipiscing aperiam, purus arcu, hendrerit suscipit proident suscipit voluptatem? Dolore perspiciatis minim morbi inventore ante? Eu, quas, diam iaculis itaque purus consequatur ullamcorper, pellentesque dicta, mi reiciendis curae fugit! Dolorem quasi! Accusamus soluta modi accusamus, rem id, interdum aliquid corrupti ultrices dapibus odit, varius voluptas, itaque. Ligula lacus molestie.</p>
        <p>Massa sollicitudin impedit deleniti nascetur delectus sequi dolore vestibulum? Vitae, ultricies eaque, tenetur! Elit blandit? Optio, penatibus voluptatem sociosqu error voluptates lectus quia praesent esse impedit sapien elementum, veniam hac, commodi porro, ante senectus dignissim! Dictum, rem illo fames? Aliqua quo neque! Do eius nullam dolorum habitasse. Eget? Tellus molestie, aliquam ad? Duis sagittis dictumst quibusdam expedita penatibus dignissimos delectus.</p>
        <p>Cumque reiciendis cupiditate rerum suscipit? Fugiat rem alias ea laudantium aliqua laoreet, minima reprehenderit, netus! Asperiores aliquid ornare consequuntur accumsan, eu ullamcorper laboris voluptates. Minima! Sem morbi quae! Dolores irure, dui suspendisse, fuga habitasse quia, facere diam aliquip? Doloribus! Cubilia facere eius pariatur euismod libero, quisquam repellendus facilisi tempor placeat nec mollit, harum sem quam fames. Ultrices porta rutrum enim.</p>
        <p>Eum perspiciatis proin veniam natus, aenean quam inventore, ad, provident saepe fugiat congue, asperiores diam! Sodales eros mi dolores sit architecto sem parturient animi primis eligendi, culpa in sodales iaculis volutpat voluptate ad architecto pede id. Officia cum, recusandae laboris provident ridiculus, adipiscing quam, at risus exercitationem ullam, sapiente ligula natoque porttitor autem quidem temporibus lorem pede euismod iusto porta.</p>
        <p>Cillum massa aperiam aute, consectetur officiis taciti accusamus lacus aliquet? Dolore? Quis? Quisque earum, necessitatibus accusamus tempora nisi, possimus ridiculus voluptatem cras odio quod euismod lectus eum quae, inceptos primis. Sed totam? Nemo eiusmod libero autem. Dolorem provident felis pede, curae quia wisi taciti! Natoque volutpat, pharetra anim? Mollit voluptas? Habitant cubilia porro nulla, quisque fringilla? Harum accusamus, corrupti tempora.</p>
        <p>Laboriosam. Nostrud occaecat duis velit integer. Natoque! Ipsam non a ipsum voluptatem beatae aliqua quam viverra! Aptent, wisi nostra aptent exercitation laudantium eget blanditiis, possimus, per iusto magni totam, consequuntur? Senectus rerum, sollicitudin. Ultricies metus anim ipsam facilis itaque wisi! Ipsam commodo imperdiet ligula! Fusce, modi duis libero. Erat totam mi at doloribus metus maecenas quasi. Ultrices, aenean pellentesque maiores.</p>
        <p>Praesent scelerisque harum fermentum aperiam fermentum! Libero doloribus accusamus! Etiam, dolor quia lobortis irure velit posuere interdum! Odio molestias commodo perspiciatis aperiam auctor habitant enim, nullam! Saepe curae quia fusce! Possimus occaecat beatae, quisquam mollitia ullamco, mi proident officia do itaque sem. Earum gravida corporis, exercitationem posuere cupiditate autem consequatur. Quo rem primis, ipsam! Tristique debitis, culpa vulputate quia tellus.</p>
        <p>Suspendisse taciti euismod ornare iaculis etiam ut lorem totam cubilia morbi? Laborum, perferendis iure libero! Id sequi nostrum tempora commodi aliquam imperdiet dolorum tenetur, integer! Magni? Quasi aliquid incidunt inceptos, irure tellus duis quibusdam incidunt doloribus incidunt dignissimos adipisci? Metus porta! Etiam. Corporis facilisi vivamus ab. Auctor et similique non ex! Perferendis id nullam, ullamco vestibulum odio augue tempus augue.</p>
      </div>
    </PageTemplate>
  )
}

export default HelpPage;
